name: Generate

on:
#  push:
  pull_request:
    types: [opened, synchronize]

jobs:
  diff-map:
    name: Generates Diff Map
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - name: Executing Diff Map Action
        id: hello
        # ToDo use a specific version
        uses: cundejo/diff-map@main
        with:
          who-to-greet: 'Oliver Sosa Cano'

