name: 'Testing Script'

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  deploy:
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - name: 'Testing script'
        run: node ./tools/envs/ci-set-envs.js
