name: 'Test All'

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  deploy:
    name: 'Run Unit test in all Apps and Packages'
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - name: 'Check out code'
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: 'Setup PNPM'
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 7.3.0

      - name: 'Setup Node.js environment'
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'

      - name: 'Install dependencies'
        run: pnpm i

      - name: 'Test'
        run: pnpm test
